name: Lint with pylint

on:
  push:
    branches: [ "feature/coding_assignment" ]
  pull_request:
    branches: [ "feature/coding_assignment" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint  # Install pylint for linting
          pip install -r requirements.txt  # Install your project dependencies

      - name: Run pylint
        run: |
          pylint src/ --exit-zero
